project:
  type: website
  output-dir: docs
  resources: 
    - slides/WCDP23/banner.png
    - assets/
    - CNAME
  
execute: 
  freeze: auto

website:
  title: "David Carayon"
  favicon: assets/favicon.ico
  twitter-card:
    creator: "@david_carayon"
  navbar:
    background: "#170c3a"
    foreground: light
    left:
      - text: "Home"
        href: index.html 
        icon: house
      - text: Slides
        icon: file-earmark-easel
        href: slides.html
      - text: Blog
        icon: newspaper
        href: blog.html
      - text: CV
        icon: box-arrow-up-right
        href: https://github.com/davidcarayon/cv-typst
      - icon: box-arrow-up-right
        text: Papers
        href: https://cv.hal.science/david-carayon

    right:
      - icon: github
        href: https://github.com/davidcarayon
      - icon: gitlab
        href: https://forgemia.inra.fr/david.carayon
      - icon: linkedin
        href: https://www.linkedin.com/in/carayon-david/
format:
  html:
    theme: assets/custom.scss
    grid: 
      body-width: 900px
from: markdown+emoji



