project:
  type: website
  output-dir: docs
  resources: 
    - slides/WCDP23/banner.png
    - assets/
    - CNAME
  
execute: 
  freeze: auto

website:
  title: "David Carayon"
  favicon: assets/favicon.ico
  twitter-card:
    creator: "@david_carayon"
  navbar:
    background: "#170c3a"
    foreground: light
    left:
      - text: "Home"
        href: index.html 
        icon: house
      - text: Slides
        icon: file-earmark-easel
        href: slides.html
      - text: Blog
        icon: newspaper
        href: blog.html
      - text: Main projects
        icon: code-square
        menu:
        - text: "IDEATools"
          icon: box
          href: https://cran.r-project.org/web/packages/IDEATools/index.html
        - text: "InraeThemes"
          icon: box
          href: https://github.com/davidcarayon/InraeThemes
        - text: "quarto-inrae-extension"
          icon: file-earmark-easel
          href: https://github.com/davidcarayon/quarto-inrae-extension
        - text: "SK8"
          icon: code
          href: https://sk8.inrae.fr
      - icon: book
        text: Papers
        href: https://cv.hal.science/david-carayon

    right:
      - icon: github
        href: https://github.com/davidcarayon
      - icon: gitlab
        href: https://forgemia.inra.fr/david.carayon
      - icon: linkedin
        href: https://www.linkedin.com/in/carayon-david/
format:
  html:
    theme: assets/custom.scss
    grid: 
      body-width: 900px
from: markdown+emoji



